// <auto-generated />
using GameListApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dotnet_react.Migrations
{
    [DbContext(typeof(GameListContext))]
    [Migration("20220712212332_UpdateGameItem")]
    partial class UpdateGameItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("GameListApi.Models.GameItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InCollection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameItems");
                });
#pragma warning restore 612, 618
        }
    }
}
